name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use Node.js 18 or a newer version

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: List dist contents  # Add this step to debug
      run: ls -la dist/assets/

    - name: Create .nojekyll file
      run: touch ./dist/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true  # Add this to ensure clean deployment
